'use client';

import { useState, useEffect, useCallback } from 'react';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { 
  Search, 
  Zap, 
  RefreshCw,
  CheckCircle, 
  AlertTriangle,
  XCircle,
  ExternalLink,
  ChevronLeft,
  ChevronRight,
  AlertCircle,
  Link as LinkIcon,
  Bot,
  User
} from 'lucide-react';
import { API_URL, fetchAPI } from '@/lib/api';
import { useToast } from '@/components/ui/Toast';
import { useConfirmDialog } from '@/components/ui/ConfirmDialog';

type TabType = 'audit' | 'tools' | 'interlinking';

type SEOCheck = {
  category: 'Critical' | 'Important' | 'Optional';
  name: string;
  status: 'pass' | 'warning' | 'fail';
  message: string;
  impact: string;
};

type PostAuditResult = {
  score: number;
  passed: number;
  warnings: number;
  failed: number;
  checks: SEOCheck[];
  recommendations: string[];
};

type SiteAuditResult = {
  overallScore: number;
  posts: { id: string; title: string; score: number }[];
  globalIssues: string[];
  summary: {
    totalPosts: number;
    avgScore: number;
    postsWithIssues: number;
    criticalIssues: number;
  };
};

interface InterlinkingStats {
  totalLinks: number;
  autoGenerated: number;
  manual: number;
  postsWithLinks: number;
  avgLinksPerPost: string;
  publishedPosts: number;
  pendingPosts: number;
  settings: {
    enabled: boolean;
    minLinks: number;
    maxLinks: number;
  };
}

interface InternalLink {
  id: string;
  sourcePostId: string;
  targetUrl: string;
  anchorText: string;
  context: string;
  autoGenerated: boolean;
  createdAt: string;
  sourcePost: {
    title: string;
    slug: string;
  };
}

export default function SEOManagementPage() {
  const { success, error: showError } = useToast();
  const { dialog, confirm } = useConfirmDialog();
  const [activeTab, setActiveTab] = useState<TabType>('audit');
  const [siteAudit, setSiteAudit] = useState<SiteAuditResult | null>(null);
  const [selectedPost, setSelectedPost] = useState<string | null>(null);
  const [postAudit, setPostAudit] = useState<PostAuditResult | null>(null);
  const [stats, setStats] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [enhancing, setEnhancing] = useState(false);
  
  // Interlinking State
  const [interlinkingStats, setInterlinkingStats] = useState<InterlinkingStats | null>(null);
  const [interlinkingLinks, setInterlinkingLinks] = useState<InternalLink[]>([]);
  const [interlinkingPage, setInterlinkingPage] = useState(1);
  const [interlinkingTotalPages, setInterlinkingTotalPages] = useState(1);
  const [interlinkingRunning, setInterlinkingRunning] = useState(false);
  const [interlinkingError, setInterlinkingError] = useState('');
  const [interlinkingSuccess, setInterlinkingSuccess] = useState('');

  const fetchSiteAudit = useCallback(async () => {
    setLoading(true);
    try {
      const data = await fetchAPI('/blog/admin/seo/audit-site', { redirectOn401: false, cache: 'no-store' });
      setSiteAudit(data);
    } catch (error: any) {
      console.error('Error fetching site audit:', error);
      showError(error.message || 'Failed to fetch site audit');
    } finally {
      setLoading(false);
    }
  }, [showError]);

  const fetchPostAudit = useCallback(async (postId: string) => {
    setLoading(true);
    setSelectedPost(postId);
    try {
      const data = await fetchAPI(`/blog/admin/seo/audit/${postId}`, { redirectOn401: false, cache: 'no-store' });
      setPostAudit(data);
    } catch (error: any) {
      console.error('Error fetching post audit:', error);
      showError(error.message || 'Failed to fetch post audit');
    } finally {
      setLoading(false);
    }
  }, [showError]);

  const loadStats = useCallback(async () => {
    try {
      setLoading(true);
      const data = await fetchAPI('/blog/seo/stats', { redirectOn401: false, cache: 'no-store' });
      setStats(data);
    } catch (error: any) {
      console.error('Failed to load stats:', error);
      showError(error.message || 'Failed to load stats');
    } finally {
      setLoading(false);
    }
  }, [showError]);

  async function handleEnhanceAll() {
    confirm(
      'Enhance All Posts',
      `This will automatically enhance ${stats?.needsEnhancement || 0} posts with missing SEO fields. Continue?`,
      async () => {
        try {
          setEnhancing(true);
          const data = await fetchAPI('/blog/seo/enhance-all', { method: 'POST', redirectOn401: false, cache: 'no-store' });
          success(`Enhanced ${data.updated} posts successfully!`);
          await loadStats();
        } catch (error: any) {
          showError('Enhancement failed: ' + (error.message || 'Unknown error'));
        } finally {
          setEnhancing(false);
        }
      }
    );
  }

  // Interlinking Functions
  const loadInterlinkingData = useCallback(async () => {
    try {
      setLoading(true);

      // Fetch Stats using fetchAPI for proper session/cache handling
      const statsData = await fetchAPI('/blog/ai/interlink/stats', { 
        redirectOn401: false, 
        cache: 'no-store' 
      });
      setInterlinkingStats(statsData);

      // Fetch Links List using fetchAPI
      const listData = await fetchAPI(`/blog/ai/interlink/list?page=${interlinkingPage}&limit=20`, { 
        redirectOn401: false, 
        cache: 'no-store' 
      });
      setInterlinkingLinks(listData.links || []);
      setInterlinkingTotalPages(listData.totalPages || 1);
    } catch (err: any) {
      console.error('Error loading interlinking data:', err);
      setInterlinkingError('Failed to load interlinking data');
    } finally {
      setLoading(false);
    }
  }, [interlinkingPage]);

  const handleRunInterlinking = async () => {
    try {
      setInterlinkingRunning(true);
      setInterlinkingError('');
      setInterlinkingSuccess('');
      
      const data = await fetchAPI('/blog/ai/interlink', {
        method: 'POST',
        redirectOn401: false,
        cache: 'no-store',
      });
      
      setInterlinkingSuccess(data.message || 'Interlinking process completed');
      loadInterlinkingData(); // Refresh data
    } catch (err: any) {
      console.error('Error running interlinking:', err);
      setInterlinkingError(err.message || 'An error occurred while running interlinking');
    } finally {
      setInterlinkingRunning(false);
    }
  };

  // useEffect hooks - placed after all callback definitions to ensure proper references
  useEffect(() => {
    if (activeTab === 'audit') {
      fetchSiteAudit();
    } else if (activeTab === 'tools') {
      loadStats();
    } else if (activeTab === 'interlinking') {
      loadInterlinkingData();
    }
  }, [activeTab, fetchSiteAudit, loadStats, loadInterlinkingData]);

  useEffect(() => {
    if (activeTab === 'interlinking') {
      loadInterlinkingData();
    }
  }, [interlinkingPage, activeTab, loadInterlinkingData]);

  const getScoreColor = (score: number) => {
    if (score >= 90) return 'text-green-600 dark:text-green-400';
    if (score >= 70) return 'text-yellow-600 dark:text-yellow-400';
    if (score >= 50) return 'text-orange-600 dark:text-orange-400';
    return 'text-red-600 dark:text-red-400';
  };

  const getStatusIcon = (status: string) => {
    if (status === 'pass') return <CheckCircle className="w-5 h-5 text-green-500" />;
    if (status === 'warning') return <AlertTriangle className="w-5 h-5 text-yellow-500" />;
    return <XCircle className="w-5 h-5 text-red-500" />;
  };

  return (
    <div className="p-6">
      {dialog}
      <div className="mb-6">
        <h1 className="text-3xl font-bold text-slate-900 dark:text-white mb-2">SEO Management</h1>
        <p className="text-slate-600 dark:text-slate-400">Audit, optimize, and interlink your content for search engines</p>
      </div>

      {/* Tabs */}
      <div className="flex gap-2 mb-6 border-b border-slate-200 dark:border-slate-700">
        <button
          onClick={() => setActiveTab('audit')}
          className={`px-4 py-2 font-medium transition-colors ${
            activeTab === 'audit'
              ? 'text-blue-600 dark:text-blue-400 border-b-2 border-blue-600'
              : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200'
          }`}
        >
          <Search className="w-4 h-4 inline mr-2" />
          SEO Audit
        </button>
        <button
          onClick={() => setActiveTab('tools')}
          className={`px-4 py-2 font-medium transition-colors ${
            activeTab === 'tools'
              ? 'text-blue-600 dark:text-blue-400 border-b-2 border-blue-600'
              : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200'
          }`}
        >
          <Zap className="w-4 h-4 inline mr-2" />
          Automation Tools
        </button>
        <button
          onClick={() => setActiveTab('interlinking')}
          className={`px-4 py-2 font-medium transition-colors ${
            activeTab === 'interlinking'
              ? 'text-blue-600 dark:text-blue-400 border-b-2 border-blue-600'
              : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200'
          }`}
        >
          <LinkIcon className="w-4 h-4 inline mr-2" />
          Internal Linking
        </button>
      </div>

      {/* Tab Content */}
      {activeTab === 'audit' && (
        <div>
          {loading && (
            <div className="text-center py-12">
              <RefreshCw className="w-8 h-8 animate-spin mx-auto text-blue-500 mb-2" />
              <p className="text-slate-600 dark:text-slate-400">Loading audit data...</p>
            </div>
          )}

          {!loading && siteAudit && (
            <>
              {/* Site Overview */}
              <Card className="mb-6">
                <CardHeader>
                  <CardTitle>Site Overview</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                    <div className="p-4 bg-slate-50 dark:bg-slate-800 rounded">
                      <div className={`text-3xl font-bold ${getScoreColor(siteAudit.overallScore)}`}>
                        {siteAudit.overallScore}%
                      </div>
                      <div className="text-sm text-slate-600 dark:text-slate-400">Overall Score</div>
                    </div>
                    <div className="p-4 bg-slate-50 dark:bg-slate-800 rounded">
                      <div className="text-3xl font-bold text-slate-900 dark:text-white">
                        {siteAudit.summary.totalPosts}
                      </div>
                      <div className="text-sm text-slate-600 dark:text-slate-400">Total Posts</div>
                    </div>
                    <div className="p-4 bg-slate-50 dark:bg-slate-800 rounded">
                      <div className="text-3xl font-bold text-orange-600">
                        {siteAudit.summary.postsWithIssues}
                      </div>
                      <div className="text-sm text-slate-600 dark:text-slate-400">Posts with Issues</div>
                    </div>
                    <div className="p-4 bg-slate-50 dark:bg-slate-800 rounded">
                      <div className="text-3xl font-bold text-red-600">
                        {siteAudit.summary.criticalIssues}
                      </div>
                      <div className="text-sm text-slate-600 dark:text-slate-400">Critical Issues</div>
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* Posts List */}
              <Card>
                <CardHeader>
                  <CardTitle>Posts SEO Scores</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-2">
                    {siteAudit.posts.map((post) => (
                      <div
                        key={post.id}
                        className="flex items-center justify-between p-3 hover:bg-slate-50 dark:hover:bg-slate-800 rounded cursor-pointer"
                        onClick={() => fetchPostAudit(post.id)}
                      >
                        <div className="flex-1">
                          <div className="font-medium text-slate-900 dark:text-white">{post.title}</div>
                        </div>
                        <div className={`text-lg font-bold ${getScoreColor(post.score)}`}>
                          {post.score}%
                        </div>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>

              {/* Selected Post Details */}
              {postAudit && (
                <Card className="mt-6">
                  <CardHeader>
                    <CardTitle>Post SEO Details</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-4">
                      {postAudit.checks.map((check, idx) => (
                        <div key={idx} className="flex gap-3 p-3 border border-slate-200 dark:border-slate-700 rounded">
                          {getStatusIcon(check.status)}
                          <div className="flex-1">
                            <div className="font-medium text-slate-900 dark:text-white">{check.name}</div>
                            <div className="text-sm text-slate-600 dark:text-slate-400">{check.message}</div>
                            {check.impact && (
                              <div className="text-xs text-slate-500 dark:text-slate-500 mt-1">
                                Impact: {check.impact}
                              </div>
                            )}
                          </div>
                        </div>
                      ))}
                    </div>
                  </CardContent>
                </Card>
              )}
            </>
          )}
        </div>
      )}

      {activeTab === 'tools' && (
        <div>
          {loading ? (
            <div className="text-center py-12">
              <RefreshCw className="w-8 h-8 animate-spin mx-auto text-blue-500 mb-2" />
              <p className="text-slate-600 dark:text-slate-400">Loading stats...</p>
            </div>
          ) : (
            <>
              {/* Stats Overview */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">
                <Card>
                  <CardContent className="pt-6">
                    <div className="text-3xl font-bold text-green-600">{stats?.optimized || 0}</div>
                    <div className="text-sm text-slate-600 dark:text-slate-400">Optimized Posts</div>
                  </CardContent>
                </Card>
                <Card>
                  <CardContent className="pt-6">
                    <div className="text-3xl font-bold text-orange-600">{stats?.needsEnhancement || 0}</div>
                    <div className="text-sm text-slate-600 dark:text-slate-400">Needs Enhancement</div>
                  </CardContent>
                </Card>
                <Card>
                  <CardContent className="pt-6">
                    <div className="text-3xl font-bold text-blue-600">{stats?.total || 0}</div>
                    <div className="text-sm text-slate-600 dark:text-slate-400">Total Posts</div>
                  </CardContent>
                </Card>
              </div>

              {/* Bulk Enhancement */}
              <Card>
                <CardHeader>
                  <CardTitle>Bulk SEO Enhancement</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-slate-600 dark:text-slate-400 mb-4">
                    Automatically enhance all posts missing SEO metadata using AI-powered generation.
                  </p>
                  <Button
                    onClick={handleEnhanceAll}
                    disabled={enhancing || stats?.needsEnhancement === 0}
                    className="gap-2"
                  >
                    {enhancing ? (
                      <><RefreshCw className="w-4 h-4 animate-spin" /> Enhancing...</>
                    ) : (
                      <><Zap className="w-4 h-4" /> Enhance {stats?.needsEnhancement || 0} Posts</>
                    )}
                  </Button>
                </CardContent>
              </Card>
            </>
          )}
        </div>
      )}

      {activeTab === 'interlinking' && (
        <div className="space-y-6">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div>
              <p className="text-slate-500">
                Manage automated and manual internal links between blog posts
              </p>
            </div>
            <div className="flex gap-2">
              <Button 
                variant="outline" 
                onClick={loadInterlinkingData} 
                className='flex items-center'
              >
                <RefreshCw size={16} className="mr-2" />
                Refresh
              </Button>
              <Button 
                variant="primary" 
                onClick={handleRunInterlinking} 
                className='flex items-center'
              >
                <Bot size={16} className="mr-2" />
                Run Auto-Interlinking
              </Button>
            </div>
          </div>

          {interlinkingError && (
            <div className="bg-red-50 text-red-600 p-4 rounded-lg flex items-center gap-2">
              <AlertCircle size={20} />
              {interlinkingError}
            </div>
          )}

          {interlinkingSuccess && (
            <div className="bg-green-50 text-green-600 p-4 rounded-lg flex items-center gap-2">
              <CheckCircle size={20} />
              {interlinkingSuccess}
            </div>
          )}

          {/* Stats Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            <Card className="p-4 border-l-4 border-blue-500">
              <div className="text-slate-500 text-sm font-medium">Total Internal Links</div>
              <div className="text-2xl font-bold mt-1">{interlinkingStats?.totalLinks || 0}</div>
              <div className="text-xs text-slate-400 mt-1">Across {interlinkingStats?.postsWithLinks || 0} posts</div>
            </Card>
            
            <Card className="p-4 border-l-4 border-purple-500">
              <div className="text-slate-500 text-sm font-medium">Auto-Generated</div>
              <div className="text-2xl font-bold mt-1">{interlinkingStats?.autoGenerated || 0}</div>
              <div className="text-xs text-slate-400 mt-1">By AI algorithms</div>
            </Card>
            
            <Card className="p-4 border-l-4 border-teal-500">
              <div className="text-slate-500 text-sm font-medium">Avg. Links / Post</div>
              <div className="text-2xl font-bold mt-1">{interlinkingStats?.avgLinksPerPost || 0}</div>
              <div className="text-xs text-slate-400 mt-1">Target: {interlinkingStats?.settings.minLinks || 3}-{interlinkingStats?.settings.maxLinks || 8}</div>
            </Card>
            
            <Card className="p-4 border-l-4 border-amber-500">
              <div className="text-slate-500 text-sm font-medium">Interlinking Status</div>
              <div className="text-2xl font-bold mt-1 flex items-center gap-2">
                {interlinkingStats?.settings.enabled ? (
                  <span className="text-green-600 flex items-center gap-1"><CheckCircle size={20}/> Active</span>
                ) : (
                  <span className="text-slate-400 flex items-center gap-1"><AlertCircle size={20}/> Disabled</span>
                )}
              </div>
              <div className="text-xs text-slate-400 mt-1">Daily cron: 3:00 AM</div>
            </Card>
          </div>

          {/* Main Content */}
          <Card className="overflow-hidden">
            <div className="p-4 border-b border-slate-100 dark:border-slate-800 flex justify-between items-center bg-slate-50/50 dark:bg-slate-900/50">
              <h2 className="font-semibold text-lg">Recent Internal Links</h2>
              <div className="text-sm text-slate-500">
                Page {interlinkingPage} of {interlinkingTotalPages}
              </div>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-sm text-left">
                <thead className="text-xs text-slate-500 uppercase bg-slate-50 dark:bg-slate-900/50">
                  <tr>
                    <th className="px-4 py-3">Source Post</th>
                    <th className="px-4 py-3">Target URL</th>
                    <th className="px-4 py-3">Anchor Text</th>
                    <th className="px-4 py-3">Type</th>
                    <th className="px-4 py-3">Context</th>
                    <th className="px-4 py-3">Date</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                  {loading && interlinkingLinks.length === 0 ? (
                    <tr>
                      <td colSpan={6} className="px-4 py-8 text-center text-slate-500">
                        Loading links...
                      </td>
                    </tr>
                  ) : interlinkingLinks.length === 0 ? (
                    <tr>
                      <td colSpan={6} className="px-4 py-8 text-center text-slate-500">
                        No internal links found
                      </td>
                    </tr>
                  ) : (
                    interlinkingLinks.map((link) => (
                      <tr key={link.id} className="hover:bg-slate-50 dark:hover:bg-slate-800/50">
                        <td className="px-4 py-3 font-medium text-slate-900 dark:text-slate-100 max-w-xs truncate">
                          {link.sourcePost?.title}
                        </td>
                        <td className="px-4 py-3 text-blue-600 truncate max-w-xs">
                          <a href={link.targetUrl} target="_blank" rel="noopener noreferrer" className="flex items-center gap-1 hover:underline">
                            {link.targetUrl}
                            <ExternalLink size={12} />
                          </a>
                        </td>
                        <td className="px-4 py-3 font-medium">
                          <span className="px-2 py-1 bg-slate-100 dark:bg-slate-800 rounded text-slate-700 dark:text-slate-300">
                            {link.anchorText}
                          </span>
                        </td>
                        <td className="px-4 py-3">
                          {link.autoGenerated ? (
                            <span className="inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-medium bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-300">
                              <Bot size={12} /> Auto
                            </span>
                          ) : (
                            <span className="inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-medium bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300">
                              <User size={12} /> Manual
                            </span>
                          )}
                        </td>
                        <td className="px-4 py-3 text-slate-500 italic max-w-xs truncate">
                          "{link.context}"
                        </td>
                        <td className="px-4 py-3 text-slate-500 whitespace-nowrap">
                          {new Date(link.createdAt).toLocaleDateString()}
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>

            {/* Pagination */}
            {interlinkingTotalPages > 1 && (
              <div className="p-4 border-t border-slate-100 dark:border-slate-800 flex justify-center gap-2">
                <Button
                  variant="outline"
                  onClick={() => setInterlinkingPage(p => Math.max(1, p - 1))}
                  disabled={interlinkingPage === 1 || loading}
                  className="px-3"
                >
                  <ChevronLeft size={16} /> Previous
                </Button>
                <span className="flex items-center px-4 text-sm font-medium">
                  Page {interlinkingPage} of {interlinkingTotalPages}
                </span>
                <Button
                  variant="outline"
                  onClick={() => setInterlinkingPage(p => Math.min(interlinkingTotalPages, p + 1))}
                  disabled={interlinkingPage === interlinkingTotalPages || loading}
                  className="px-3"
                >
                  Next <ChevronRight size={16} />
                </Button>
              </div>
            )}
          </Card>
          
          {/* Information Card */}
          <Card className="p-6 bg-blue-50 dark:bg-blue-900/10 border border-blue-100 dark:border-blue-900/20">
            <h3 className="font-semibold text-blue-800 dark:text-blue-300 mb-2 flex items-center gap-2">
              <Bot size={18} />
              How Auto-Interlinking Works
            </h3>
            <ul className="list-disc list-inside text-sm text-blue-700 dark:text-blue-400 space-y-1">
              <li>The system analyzes your content daily at 3:00 AM (server time).</li>
              <li>It connects posts that share similar tags and categories.</li>
              <li>Links are created contextually where the related post title appears in the content.</li>
              <li>Existing auto-generated links are refreshed to ensure relevance.</li>
              <li>Manual links are never overwritten or deleted by the AI system.</li>
            </ul>
          </Card>
        </div>
      )}
    </div>
  );
}
