'use client';

import logger from '@/lib/logger';

import { useState, useEffect, useCallback } from 'react';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { Input } from '@/components/ui/Input';
import { 
  Search, 
  Zap, 
  RefreshCw,
  CheckCircle, 
  AlertTriangle,
  XCircle,
  ExternalLink,
  ChevronLeft,
  ChevronRight,
  AlertCircle,
  Link as LinkIcon,
  Bot,
  User
} from 'lucide-react';
import { API_URL, fetchAPI } from '@/lib/api';
import { useToast } from '@/components/ui/Toast';
import { useConfirmDialog } from '@/components/ui/ConfirmDialog';
import { getErrorMessage } from '@/lib/error-utils';

type TabType = 'audit' | 'tools' | 'interlinking' | 'sitemap';

type SEOCheck = {
  category: 'Critical' | 'Important' | 'Optional';
  name: string;
  status: 'pass' | 'warning' | 'fail';
  message: string;
  impact: string;
};

type PostAuditResult = {
  score: number;
  passed: number;
  warnings: number;
  failed: number;
  checks: SEOCheck[];
  recommendations: string[];
};

type SiteAuditResult = {
  overallScore: number;
  posts: { id: string; title: string; score: number }[];
  globalIssues: string[];
  summary: {
    totalPosts: number;
    avgScore: number;
    postsWithIssues: number;
    criticalIssues: number;
  };
};

interface InterlinkingStats {
  totalLinks: number;
  autoGenerated: number;
  manual: number;
  postsWithLinks: number;
  avgLinksPerPost: number;
  publishedPosts: number;
  pendingPosts: number;
  settings: {
    enabled: boolean;
    minLinks: number;
    maxLinks: number;
  };
}

interface InternalLink {
  id: string;
  sourcePostId: string;
  targetUrl: string;
  anchorText: string;
  context: string;
  autoGenerated: boolean;
  createdAt: string;
  sourcePost?: {
    title?: string;
    slug?: string;
  };
}

type SeoStats = {
  optimized: number;
  needsEnhancement: number;
  total: number;
};

type SitemapStats = {
  totalUrls: number;
  staticPages?: number;
  blogPosts?: number;
  categories?: number;
  tags?: number;
  pages?: number;
  customUrls?: number;
  staticCustomUrls?: number;
  baseUrl?: string;
  lastGenerated?: string;
  enabled?: boolean;
};

type SitemapCustomUrl = {
  loc: string;
  changefreq: string;
  priority: string;
};

type SitemapConfigState = {
  enabled: boolean;
  baseUrl: string;
  include: {
    staticPages: boolean;
    blogPosts: boolean;
    categories: boolean;
    tags: boolean;
    pages: boolean;
  };
  exclude: {
    posts: string;
    categories: string;
    tags: string;
    pages: string;
  };
  customUrls: SitemapCustomUrl[];
};

const DEFAULT_SEO_STATS: SeoStats = {
  optimized: 0,
  needsEnhancement: 0,
  total: 0,
};

const DEFAULT_INTERLINKING_STATS: InterlinkingStats = {
  totalLinks: 0,
  autoGenerated: 0,
  manual: 0,
  postsWithLinks: 0,
  avgLinksPerPost: 0,
  publishedPosts: 0,
  pendingPosts: 0,
  settings: {
    enabled: false,
    minLinks: 3,
    maxLinks: 8,
  },
};

const CHANGEFREQ_OPTIONS = ['always', 'hourly', 'daily', 'weekly', 'monthly', 'yearly', 'never'] as const;

const DEFAULT_SITEMAP_CONFIG: SitemapConfigState = {
  enabled: true,
  baseUrl: '',
  include: {
    staticPages: true,
    blogPosts: true,
    categories: true,
    tags: true,
    pages: true,
  },
  exclude: {
    posts: '',
    categories: '',
    tags: '',
    pages: '',
  },
  customUrls: [],
};

const isRecord = (value: unknown): value is Record<string, unknown> => (
  value !== null && typeof value === 'object' && !Array.isArray(value)
);

const parseNumber = (value: unknown, fallback = 0): number => (
  typeof value === 'number' && Number.isFinite(value) ? value : fallback
);

const parseString = (value: unknown, fallback = ''): string => (
  typeof value === 'string' ? value : fallback
);

const parseBoolean = (value: unknown, fallback = false): boolean => (
  typeof value === 'boolean' ? value : fallback
);

const parseSeoStats = (value: unknown): SeoStats => {
  if (!isRecord(value)) {
    return DEFAULT_SEO_STATS;
  }
  return {
    optimized: parseNumber(value.optimized),
    needsEnhancement: parseNumber(value.needsEnhancement),
    total: parseNumber(value.total),
  };
};

const parseSeoCheck = (value: unknown): SEOCheck | null => {
  if (!isRecord(value)) {
    return null;
  }
  const categoryRaw = parseString(value.category);
  const statusRaw = parseString(value.status);
  const category: SEOCheck['category'] = categoryRaw === 'Critical' || categoryRaw === 'Important' || categoryRaw === 'Optional'
    ? categoryRaw
    : 'Optional';
  const status: SEOCheck['status'] = statusRaw === 'pass' || statusRaw === 'warning' || statusRaw === 'fail'
    ? statusRaw
    : 'fail';
  return {
    category,
    name: parseString(value.name),
    status,
    message: parseString(value.message),
    impact: parseString(value.impact),
  };
};

const parsePostAuditResult = (value: unknown): PostAuditResult | null => {
  if (!isRecord(value)) {
    return null;
  }
  const checks = Array.isArray(value.checks)
    ? value.checks.map(parseSeoCheck).filter((check): check is SEOCheck => !!check)
    : [];
  const recommendations = Array.isArray(value.recommendations)
    ? value.recommendations.filter((rec): rec is string => typeof rec === 'string')
    : [];
  return {
    score: parseNumber(value.score),
    passed: parseNumber(value.passed),
    warnings: parseNumber(value.warnings),
    failed: parseNumber(value.failed),
    checks,
    recommendations,
  };
};

const parseSiteAuditResult = (value: unknown): SiteAuditResult | null => {
  if (!isRecord(value)) {
    return null;
  }
  const posts = Array.isArray(value.posts)
    ? value.posts
        .map((post) => {
          if (!isRecord(post)) {
            return null;
          }
          const id = parseString(post.id);
          if (!id) {
            return null;
          }
          return {
            id,
            title: parseString(post.title, 'Untitled'),
            score: parseNumber(post.score),
          };
        })
        .filter((post): post is { id: string; title: string; score: number } => !!post)
    : [];
  const summaryRaw = isRecord(value.summary) ? value.summary : {};
  return {
    overallScore: parseNumber(value.overallScore),
    posts,
    globalIssues: Array.isArray(value.globalIssues)
      ? value.globalIssues.filter((issue): issue is string => typeof issue === 'string')
      : [],
    summary: {
      totalPosts: parseNumber(summaryRaw.totalPosts),
      avgScore: parseNumber(summaryRaw.avgScore),
      postsWithIssues: parseNumber(summaryRaw.postsWithIssues),
      criticalIssues: parseNumber(summaryRaw.criticalIssues),
    },
  };
};

const parseInterlinkingStats = (value: unknown): InterlinkingStats => {
  if (!isRecord(value)) {
    return DEFAULT_INTERLINKING_STATS;
  }
  const settingsRaw = isRecord(value.settings) ? value.settings : {};
  return {
    totalLinks: parseNumber(value.totalLinks),
    autoGenerated: parseNumber(value.autoGenerated),
    manual: parseNumber(value.manual),
    postsWithLinks: parseNumber(value.postsWithLinks),
    avgLinksPerPost: parseNumber(value.avgLinksPerPost),
    publishedPosts: parseNumber(value.publishedPosts),
    pendingPosts: parseNumber(value.pendingPosts),
    settings: {
      enabled: parseBoolean(settingsRaw.enabled),
      minLinks: parseNumber(settingsRaw.minLinks, 3),
      maxLinks: parseNumber(settingsRaw.maxLinks, 8),
    },
  };
};

const parseInternalLink = (value: unknown): InternalLink | null => {
  if (!isRecord(value)) {
    return null;
  }
  const sourcePostRaw = isRecord(value.sourcePost) ? value.sourcePost : null;
  const id = parseString(value.id) || parseString(value.targetUrl) || parseString(value.sourcePostId);
  if (!id) {
    return null;
  }
  return {
    id,
    sourcePostId: parseString(value.sourcePostId),
    targetUrl: parseString(value.targetUrl),
    anchorText: parseString(value.anchorText),
    context: parseString(value.context),
    autoGenerated: parseBoolean(value.autoGenerated),
    createdAt: parseString(value.createdAt),
    sourcePost: sourcePostRaw
      ? {
          title: parseString(sourcePostRaw.title),
          slug: parseString(sourcePostRaw.slug),
        }
      : undefined,
  };
};

const parseInternalLinkList = (value: unknown): InternalLink[] => {
  if (!Array.isArray(value)) {
    return [];
  }
  return value.map(parseInternalLink).filter((link): link is InternalLink => !!link);
};

const parseSitemapStats = (value: unknown): SitemapStats => {
  if (!isRecord(value)) {
    return {
      totalUrls: 0,
    };
  }
  return {
    totalUrls: parseNumber(value.totalUrls),
    staticPages: parseNumber(value.staticPages),
    blogPosts: parseNumber(value.blogPosts),
    categories: parseNumber(value.categories),
    tags: parseNumber(value.tags),
    pages: parseNumber(value.pages),
    customUrls: parseNumber(value.customUrls),
    staticCustomUrls: parseNumber(value.staticCustomUrls),
    baseUrl: parseString(value.baseUrl),
    lastGenerated: parseString(value.lastGenerated),
    enabled: typeof value.enabled === 'boolean' ? value.enabled : undefined,
  };
};

const toCsv = (value: unknown): string => (
  Array.isArray(value)
    ? value.filter((item): item is string => typeof item === 'string').join(', ')
    : ''
);

const parseSitemapConfig = (value: unknown): SitemapConfigState => {
  if (!isRecord(value)) {
    return { ...DEFAULT_SITEMAP_CONFIG };
  }
  const includeRaw = isRecord(value.include) ? value.include : {};
  const excludeRaw = isRecord(value.exclude) ? value.exclude : {};
  const customUrls = Array.isArray(value.customUrls)
    ? value.customUrls
        .filter(isRecord)
        .map((entry) => ({
          loc: parseString(entry.loc),
          changefreq: parseString(entry.changefreq) || 'monthly',
          priority: typeof entry.priority === 'number' ? entry.priority.toFixed(1) : '0.5',
        }))
        .filter((entry) => entry.loc)
    : [];

  return {
    enabled: typeof value.enabled === 'boolean' ? value.enabled : DEFAULT_SITEMAP_CONFIG.enabled,
    baseUrl: parseString(value.baseUrl),
    include: {
      staticPages: typeof includeRaw.staticPages === 'boolean' ? includeRaw.staticPages : DEFAULT_SITEMAP_CONFIG.include.staticPages,
      blogPosts: typeof includeRaw.blogPosts === 'boolean' ? includeRaw.blogPosts : DEFAULT_SITEMAP_CONFIG.include.blogPosts,
      categories: typeof includeRaw.categories === 'boolean' ? includeRaw.categories : DEFAULT_SITEMAP_CONFIG.include.categories,
      tags: typeof includeRaw.tags === 'boolean' ? includeRaw.tags : DEFAULT_SITEMAP_CONFIG.include.tags,
      pages: typeof includeRaw.pages === 'boolean' ? includeRaw.pages : DEFAULT_SITEMAP_CONFIG.include.pages,
    },
    exclude: {
      posts: toCsv(excludeRaw.posts),
      categories: toCsv(excludeRaw.categories),
      tags: toCsv(excludeRaw.tags),
      pages: toCsv(excludeRaw.pages),
    },
    customUrls,
  };
};

export default function SEOManagementPage() {
  const { success, error: showError } = useToast();
  const { dialog, confirm } = useConfirmDialog();
  const [activeTab, setActiveTab] = useState<TabType>('audit');
  const [siteAudit, setSiteAudit] = useState<SiteAuditResult | null>(null);
  const [selectedPost, setSelectedPost] = useState<string | null>(null);
  const [postAudit, setPostAudit] = useState<PostAuditResult | null>(null);
  const [stats, setStats] = useState<SeoStats | null>(null);
  const [loading, setLoading] = useState(false);
  const [enhancing, setEnhancing] = useState(false);
  
  // Interlinking State
  const [interlinkingStats, setInterlinkingStats] = useState<InterlinkingStats | null>(null);
  const [interlinkingLinks, setInterlinkingLinks] = useState<InternalLink[]>([]);
  const [interlinkingPage, setInterlinkingPage] = useState(1);
  const [interlinkingTotalPages, setInterlinkingTotalPages] = useState(1);
  const [interlinkingRunning, setInterlinkingRunning] = useState(false);
  const [interlinkingError, setInterlinkingError] = useState('');
  const [interlinkingSuccess, setInterlinkingSuccess] = useState('');

  const [sitemapConfig, setSitemapConfig] = useState<SitemapConfigState>({ ...DEFAULT_SITEMAP_CONFIG });
  const [sitemapStats, setSitemapStats] = useState<SitemapStats | null>(null);
  const [sitemapLoading, setSitemapLoading] = useState(false);
  const [sitemapSaving, setSitemapSaving] = useState(false);
  const [sitemapMessage, setSitemapMessage] = useState('');

  const fetchSiteAudit = useCallback(async () => {
    setLoading(true);
    try {
      const data = await fetchAPI('/blog/admin/seo/audit-site', { redirectOn401: false, cache: 'no-store' });
      setSiteAudit(parseSiteAuditResult(data));
    } catch (error: unknown) {
      logger.error('Error fetching site audit:', error);
      showError(getErrorMessage(error, 'Failed to fetch site audit'));
    } finally {
      setLoading(false);
    }
  }, [showError]);

  const fetchPostAudit = useCallback(async (postId: string) => {
    setLoading(true);
    setSelectedPost(postId);
    try {
      const data = await fetchAPI(`/blog/admin/seo/audit/${postId}`, { redirectOn401: false, cache: 'no-store' });
      setPostAudit(parsePostAuditResult(data));
    } catch (error: unknown) {
      logger.error('Error fetching post audit:', error);
      showError(getErrorMessage(error, 'Failed to fetch post audit'));
    } finally {
      setLoading(false);
    }
  }, [showError]);

  const loadStats = useCallback(async () => {
    try {
      setLoading(true);
      const data = await fetchAPI('/blog/seo/stats', { redirectOn401: false, cache: 'no-store' });
      setStats(parseSeoStats(data));
    } catch (error: unknown) {
      logger.error('Failed to load stats:', error);
      showError(getErrorMessage(error, 'Failed to load stats'));
    } finally {
      setLoading(false);
    }
  }, [showError]);

  async function handleEnhanceAll() {
    confirm(
      'Enhance All Posts',
      `This will automatically enhance ${stats?.needsEnhancement || 0} posts with missing SEO fields. Continue?`,
      async () => {
        try {
          setEnhancing(true);
          const data = await fetchAPI('/blog/seo/enhance-all', { method: 'POST', redirectOn401: false, cache: 'no-store' });
          const updatedCount = parseNumber(isRecord(data) ? data.updated : 0);
          success(`Enhanced ${updatedCount} posts successfully!`);
          await loadStats();
        } catch (error: unknown) {
          showError('Enhancement failed: ' + getErrorMessage(error, 'Unknown error'));
        } finally {
          setEnhancing(false);
        }
      }
    );
  }

  // Interlinking Functions
  const loadInterlinkingData = useCallback(async () => {
    try {
      setLoading(true);

      // Fetch Stats using fetchAPI for proper session/cache handling
      const statsData = await fetchAPI('/blog/ai/interlink/stats', { 
        redirectOn401: false, 
        cache: 'no-store' 
      });
      setInterlinkingStats(parseInterlinkingStats(statsData));

      // Fetch Links List using fetchAPI
      const listData = await fetchAPI(`/blog/ai/interlink/list?page=${interlinkingPage}&limit=20`, { 
        redirectOn401: false, 
        cache: 'no-store' 
      });
      if (isRecord(listData)) {
        setInterlinkingLinks(parseInternalLinkList(listData.links));
        setInterlinkingTotalPages(parseNumber(listData.totalPages, 1));
      } else {
        setInterlinkingLinks([]);
        setInterlinkingTotalPages(1);
      }
    } catch (err: unknown) {
      logger.error('Error loading interlinking data:', err);
      setInterlinkingError('Failed to load interlinking data');
    } finally {
      setLoading(false);
    }
  }, [interlinkingPage]);

  const handleRunInterlinking = async () => {
    try {
      setInterlinkingRunning(true);
      setInterlinkingError('');
      setInterlinkingSuccess('');
      
      const data = await fetchAPI('/blog/ai/interlink', {
        method: 'POST',
        redirectOn401: false,
        cache: 'no-store',
      });
      
      const successMessage = isRecord(data) ? parseString(data.message) : '';
      setInterlinkingSuccess(successMessage || 'Interlinking process completed');
      loadInterlinkingData(); // Refresh data
    } catch (err: unknown) {
      logger.error('Error running interlinking:', err);
      setInterlinkingError(getErrorMessage(err, 'An error occurred while running interlinking'));
    } finally {
      setInterlinkingRunning(false);
    }
  };

  const parseCsvList = (value: string) => (
    value
      .split(',')
      .map((item) => item.trim())
      .filter(Boolean)
  );

  const loadSitemapConfig = useCallback(async () => {
    setSitemapLoading(true);
    try {
      const data = await fetchAPI('/settings', { redirectOn401: false, cache: 'no-store' });
      const config = isRecord(data) ? parseSitemapConfig(data.sitemapConfig) : { ...DEFAULT_SITEMAP_CONFIG };
      setSitemapConfig(config);
      setSitemapMessage('');
    } catch (err: unknown) {
      logger.error('Failed to load sitemap config', err);
      showError(getErrorMessage(err, 'Failed to load sitemap settings'));
    } finally {
      setSitemapLoading(false);
    }
  }, [showError]);

  const loadSitemapStats = useCallback(async () => {
    try {
      const data = await fetchAPI('/tasks/sitemap/stats', { redirectOn401: false, cache: 'no-store' });
      setSitemapStats(parseSitemapStats(data));
    } catch (err: unknown) {
      logger.error('Failed to load sitemap stats', err);
    }
  }, []);

  const handleSaveSitemapConfig = async () => {
    setSitemapSaving(true);
    setSitemapMessage('');

    try {
      const payload = {
        sitemapConfig: {
          enabled: sitemapConfig.enabled,
          baseUrl: sitemapConfig.baseUrl.trim() || undefined,
          include: { ...sitemapConfig.include },
          exclude: {
            posts: parseCsvList(sitemapConfig.exclude.posts),
            categories: parseCsvList(sitemapConfig.exclude.categories),
            tags: parseCsvList(sitemapConfig.exclude.tags),
            pages: parseCsvList(sitemapConfig.exclude.pages),
          },
          customUrls: sitemapConfig.customUrls
            .filter((entry) => entry.loc.trim())
            .map((entry) => {
              const parsedPriority = Number.parseFloat(entry.priority);
              const priority = Number.isFinite(parsedPriority)
                ? Math.min(1, Math.max(0, parsedPriority))
                : 0.5;
              return {
                loc: entry.loc.trim(),
                changefreq: entry.changefreq,
                priority,
              };
            }),
        },
      };

      await fetchAPI('/settings', {
        method: 'PUT',
        body: JSON.stringify(payload),
        redirectOn401: false,
        cache: 'no-store',
      });
      success('Sitemap settings saved');
      setSitemapMessage('Settings saved. Generate a new sitemap to apply changes.');
      loadSitemapStats();
    } catch (err: unknown) {
      logger.error('Failed to save sitemap config', err);
      showError(getErrorMessage(err, 'Failed to save sitemap settings'));
    } finally {
      setSitemapSaving(false);
    }
  };

  const handleGenerateSitemap = async () => {
    setSitemapSaving(true);
    try {
      const data = await fetchAPI('/tasks/sitemap/generate', {
        method: 'POST',
        redirectOn401: false,
        cache: 'no-store',
      });
      const stats = isRecord(data) ? parseSitemapStats(data.stats) : null;
      if (stats) {
        setSitemapStats(stats);
      } else {
        loadSitemapStats();
      }
      success('Sitemap generated successfully');
    } catch (err: unknown) {
      logger.error('Failed to generate sitemap', err);
      showError(getErrorMessage(err, 'Failed to generate sitemap'));
    } finally {
      setSitemapSaving(false);
    }
  };

  // useEffect hooks - placed after all callback definitions to ensure proper references
  useEffect(() => {
    if (activeTab === 'audit') {
      fetchSiteAudit();
    } else if (activeTab === 'tools') {
      loadStats();
    } else if (activeTab === 'interlinking') {
      loadInterlinkingData();
    } else if (activeTab === 'sitemap') {
      loadSitemapConfig();
      loadSitemapStats();
    }
  }, [activeTab, fetchSiteAudit, loadStats, loadInterlinkingData, loadSitemapConfig, loadSitemapStats]);

  useEffect(() => {
    if (activeTab === 'interlinking') {
      loadInterlinkingData();
    }
  }, [interlinkingPage, activeTab, loadInterlinkingData]);

  const getScoreColor = (score: number) => {
    if (score >= 90) return 'text-green-600 dark:text-green-400';
    if (score >= 70) return 'text-yellow-600 dark:text-yellow-400';
    if (score >= 50) return 'text-orange-600 dark:text-orange-400';
    return 'text-red-600 dark:text-red-400';
  };

  const getStatusIcon = (status: string) => {
    if (status === 'pass') return <CheckCircle className="w-5 h-5 text-green-500" />;
    if (status === 'warning') return <AlertTriangle className="w-5 h-5 text-yellow-500" />;
    return <XCircle className="w-5 h-5 text-red-500" />;
  };

  return (
    <div className="p-6">
      {dialog}
      <div className="mb-6">
        <h1 className="text-3xl font-bold text-slate-900 dark:text-white mb-2">SEO Management</h1>
        <p className="text-slate-600 dark:text-slate-400">Audit, optimize, and interlink your content for search engines</p>
      </div>

      {/* Tabs */}
      <div className="flex gap-2 mb-6 border-b border-slate-200 dark:border-slate-700">
        <button
          onClick={() => setActiveTab('audit')}
          className={`px-4 py-2 font-medium transition-colors ${
            activeTab === 'audit'
              ? 'text-blue-600 dark:text-blue-400 border-b-2 border-blue-600'
              : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200'
          }`}
        >
          <Search className="w-4 h-4 inline mr-2" />
          SEO Audit
        </button>
        <button
          onClick={() => setActiveTab('tools')}
          className={`px-4 py-2 font-medium transition-colors ${
            activeTab === 'tools'
              ? 'text-blue-600 dark:text-blue-400 border-b-2 border-blue-600'
              : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200'
          }`}
        >
          <Zap className="w-4 h-4 inline mr-2" />
          Automation Tools
        </button>
        <button
          onClick={() => setActiveTab('interlinking')}
          className={`px-4 py-2 font-medium transition-colors ${
            activeTab === 'interlinking'
              ? 'text-blue-600 dark:text-blue-400 border-b-2 border-blue-600'
              : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200'
          }`}
        >
          <LinkIcon className="w-4 h-4 inline mr-2" />
          Internal Linking
        </button>
        <button
          onClick={() => setActiveTab('sitemap')}
          className={`px-4 py-2 font-medium transition-colors ${
            activeTab === 'sitemap'
              ? 'text-blue-600 dark:text-blue-400 border-b-2 border-blue-600'
              : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200'
          }`}
        >
          <ExternalLink className="w-4 h-4 inline mr-2" />
          Sitemap
        </button>
      </div>

      {/* Tab Content */}
      {activeTab === 'audit' && (
        <div>
          {loading && (
            <div className="text-center py-12">
              <RefreshCw className="w-8 h-8 animate-spin mx-auto text-blue-500 mb-2" />
              <p className="text-slate-600 dark:text-slate-400">Loading audit data...</p>
            </div>
          )}

          {!loading && siteAudit && (
            <>
              {/* Site Overview */}
              <Card className="mb-6">
                <CardHeader>
                  <CardTitle>Site Overview</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                    <div className="p-4 bg-slate-50 dark:bg-slate-800 rounded">
                      <div className={`text-3xl font-bold ${getScoreColor(siteAudit.overallScore)}`}>
                        {siteAudit.overallScore}%
                      </div>
                      <div className="text-sm text-slate-600 dark:text-slate-400">Overall Score</div>
                    </div>
                    <div className="p-4 bg-slate-50 dark:bg-slate-800 rounded">
                      <div className="text-3xl font-bold text-slate-900 dark:text-white">
                        {siteAudit.summary.totalPosts}
                      </div>
                      <div className="text-sm text-slate-600 dark:text-slate-400">Total Posts</div>
                    </div>
                    <div className="p-4 bg-slate-50 dark:bg-slate-800 rounded">
                      <div className="text-3xl font-bold text-orange-600">
                        {siteAudit.summary.postsWithIssues}
                      </div>
                      <div className="text-sm text-slate-600 dark:text-slate-400">Posts with Issues</div>
                    </div>
                    <div className="p-4 bg-slate-50 dark:bg-slate-800 rounded">
                      <div className="text-3xl font-bold text-red-600">
                        {siteAudit.summary.criticalIssues}
                      </div>
                      <div className="text-sm text-slate-600 dark:text-slate-400">Critical Issues</div>
                    </div>
                  </div>
                </CardContent>
              </Card>

              <Card className="mb-6 border-dashed">
                <CardHeader>
                  <CardTitle>SEO Operations TODOs</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3 text-sm text-slate-600 dark:text-slate-300">
                    <div className="flex flex-wrap items-center justify-between gap-2">
                      <span>Public blog pagination + tag/category filters</span>
                      <Badge variant="warning" size="sm">In progress</Badge>
                    </div>
                    <div className="flex flex-wrap items-center justify-between gap-2">
                      <span>Tag hierarchy health checks and duplicate merge automation</span>
                      <Badge variant="warning" size="sm">Queued</Badge>
                    </div>
                    <div className="flex flex-wrap items-center justify-between gap-2">
                      <span>Cron job health reporting and alert hooks</span>
                      <Badge variant="warning" size="sm">Queued</Badge>
                    </div>
                    <div className="flex flex-wrap items-center justify-between gap-2">
                      <span>Sitemap governance + exclusion lists (admin managed)</span>
                      <Badge variant="success" size="sm">Active</Badge>
                    </div>
                    <div className="flex flex-wrap items-center justify-between gap-2">
                      <span>Dark mode persistence on refresh</span>
                      <Badge variant="success" size="sm">Applied</Badge>
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* Posts List */}
              <Card>
                <CardHeader>
                  <CardTitle>Posts SEO Scores</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-2">
                    {siteAudit.posts.map((post) => (
                      <div
                        key={post.id}
                        className="flex items-center justify-between p-3 hover:bg-slate-50 dark:hover:bg-slate-800 rounded cursor-pointer"
                        onClick={() => fetchPostAudit(post.id)}
                      >
                        <div className="flex-1">
                          <div className="font-medium text-slate-900 dark:text-white">{post.title}</div>
                        </div>
                        <div className={`text-lg font-bold ${getScoreColor(post.score)}`}>
                          {post.score}%
                        </div>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>

              {/* Selected Post Details */}
              {postAudit && (
                <Card className="mt-6">
                  <CardHeader>
                    <CardTitle>Post SEO Details</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-4">
                      {postAudit.checks.map((check, idx) => (
                        <div key={idx} className="flex gap-3 p-3 border border-slate-200 dark:border-slate-700 rounded">
                          {getStatusIcon(check.status)}
                          <div className="flex-1">
                            <div className="font-medium text-slate-900 dark:text-white">{check.name}</div>
                            <div className="text-sm text-slate-600 dark:text-slate-400">{check.message}</div>
                            {check.impact && (
                              <div className="text-xs text-slate-500 dark:text-slate-500 mt-1">
                                Impact: {check.impact}
                              </div>
                            )}
                          </div>
                        </div>
                      ))}
                    </div>
                  </CardContent>
                </Card>
              )}
            </>
          )}
        </div>
      )}

      {activeTab === 'tools' && (
        <div>
          {loading ? (
            <div className="text-center py-12">
              <RefreshCw className="w-8 h-8 animate-spin mx-auto text-blue-500 mb-2" />
              <p className="text-slate-600 dark:text-slate-400">Loading stats...</p>
            </div>
          ) : (
            <>
              {/* Stats Overview */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">
                <Card>
                  <CardContent className="pt-6">
                    <div className="text-3xl font-bold text-green-600">{stats?.optimized || 0}</div>
                    <div className="text-sm text-slate-600 dark:text-slate-400">Optimized Posts</div>
                  </CardContent>
                </Card>
                <Card>
                  <CardContent className="pt-6">
                    <div className="text-3xl font-bold text-orange-600">{stats?.needsEnhancement || 0}</div>
                    <div className="text-sm text-slate-600 dark:text-slate-400">Needs Enhancement</div>
                  </CardContent>
                </Card>
                <Card>
                  <CardContent className="pt-6">
                    <div className="text-3xl font-bold text-blue-600">{stats?.total || 0}</div>
                    <div className="text-sm text-slate-600 dark:text-slate-400">Total Posts</div>
                  </CardContent>
                </Card>
              </div>

              {/* Bulk Enhancement */}
              <Card>
                <CardHeader>
                  <CardTitle>Bulk SEO Enhancement</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-slate-600 dark:text-slate-400 mb-4">
                    Automatically enhance all posts missing SEO metadata using AI-powered generation.
                  </p>
                  <Button
                    onClick={handleEnhanceAll}
                    disabled={enhancing || stats?.needsEnhancement === 0}
                    className="gap-2"
                  >
                    {enhancing ? (
                      <><RefreshCw className="w-4 h-4 animate-spin" /> Enhancing...</>
                    ) : (
                      <><Zap className="w-4 h-4" /> Enhance {stats?.needsEnhancement || 0} Posts</>
                    )}
                  </Button>
                </CardContent>
              </Card>
            </>
          )}
        </div>
      )}

      {activeTab === 'interlinking' && (
        <div className="space-y-6">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div>
              <p className="text-slate-500">
                Manage automated and manual internal links between blog posts
              </p>
            </div>
            <div className="flex gap-2">
              <Button 
                variant="outline" 
                onClick={loadInterlinkingData} 
                className='flex items-center'
              >
                <RefreshCw size={16} className="mr-2" />
                Refresh
              </Button>
              <Button 
                variant="primary" 
                onClick={handleRunInterlinking} 
                className='flex items-center'
              >
                <Bot size={16} className="mr-2" />
                Run Auto-Interlinking
              </Button>
            </div>
          </div>

          {interlinkingError && (
            <div className="bg-red-50 text-red-600 p-4 rounded-lg flex items-center gap-2">
              <AlertCircle size={20} />
              {interlinkingError}
            </div>
          )}

          {interlinkingSuccess && (
            <div className="bg-green-50 text-green-600 p-4 rounded-lg flex items-center gap-2">
              <CheckCircle size={20} />
              {interlinkingSuccess}
            </div>
          )}

          {/* Stats Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            <Card className="p-4 border-l-4 border-blue-500">
              <div className="text-slate-500 text-sm font-medium">Total Internal Links</div>
              <div className="text-2xl font-bold mt-1">{interlinkingStats?.totalLinks || 0}</div>
              <div className="text-xs text-slate-400 mt-1">Across {interlinkingStats?.postsWithLinks || 0} posts</div>
            </Card>
            
            <Card className="p-4 border-l-4 border-purple-500">
              <div className="text-slate-500 text-sm font-medium">Auto-Generated</div>
              <div className="text-2xl font-bold mt-1">{interlinkingStats?.autoGenerated || 0}</div>
              <div className="text-xs text-slate-400 mt-1">By AI algorithms</div>
            </Card>
            
            <Card className="p-4 border-l-4 border-teal-500">
              <div className="text-slate-500 text-sm font-medium">Avg. Links / Post</div>
              <div className="text-2xl font-bold mt-1">{interlinkingStats?.avgLinksPerPost || 0}</div>
              <div className="text-xs text-slate-400 mt-1">Target: {interlinkingStats?.settings.minLinks || 3}-{interlinkingStats?.settings.maxLinks || 8}</div>
            </Card>
            
            <Card className="p-4 border-l-4 border-amber-500">
              <div className="text-slate-500 text-sm font-medium">Interlinking Status</div>
              <div className="text-2xl font-bold mt-1 flex items-center gap-2">
                {interlinkingStats?.settings.enabled ? (
                  <span className="text-green-600 flex items-center gap-1"><CheckCircle size={20}/> Active</span>
                ) : (
                  <span className="text-slate-400 flex items-center gap-1"><AlertCircle size={20}/> Disabled</span>
                )}
              </div>
              <div className="text-xs text-slate-400 mt-1">Daily cron: 3:00 AM</div>
            </Card>
          </div>

          {/* Main Content */}
          <Card className="overflow-hidden">
            <div className="p-4 border-b border-slate-100 dark:border-slate-800 flex justify-between items-center bg-slate-50/50 dark:bg-slate-900/50">
              <h2 className="font-semibold text-lg">Recent Internal Links</h2>
              <div className="text-sm text-slate-500">
                Page {interlinkingPage} of {interlinkingTotalPages}
              </div>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-sm text-left">
                <thead className="text-xs text-slate-500 uppercase bg-slate-50 dark:bg-slate-900/50">
                  <tr>
                    <th className="px-4 py-3">Source Post</th>
                    <th className="px-4 py-3">Target URL</th>
                    <th className="px-4 py-3">Anchor Text</th>
                    <th className="px-4 py-3">Type</th>
                    <th className="px-4 py-3">Context</th>
                    <th className="px-4 py-3">Date</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                  {loading && interlinkingLinks.length === 0 ? (
                    <tr>
                      <td colSpan={6} className="px-4 py-8 text-center text-slate-500">
                        Loading links...
                      </td>
                    </tr>
                  ) : interlinkingLinks.length === 0 ? (
                    <tr>
                      <td colSpan={6} className="px-4 py-8 text-center text-slate-500">
                        No internal links found
                      </td>
                    </tr>
                  ) : (
                    interlinkingLinks.map((link) => (
                      <tr key={link.id} className="hover:bg-slate-50 dark:hover:bg-slate-800/50">
                        <td className="px-4 py-3 font-medium text-slate-900 dark:text-slate-100 max-w-xs truncate">
                          {link.sourcePost?.title}
                        </td>
                        <td className="px-4 py-3 text-blue-600 truncate max-w-xs">
                          <a href={link.targetUrl} target="_blank" rel="noopener noreferrer" className="flex items-center gap-1 hover:underline">
                            {link.targetUrl}
                            <ExternalLink size={12} />
                          </a>
                        </td>
                        <td className="px-4 py-3 font-medium">
                          <span className="px-2 py-1 bg-slate-100 dark:bg-slate-800 rounded text-slate-700 dark:text-slate-300">
                            {link.anchorText}
                          </span>
                        </td>
                        <td className="px-4 py-3">
                          {link.autoGenerated ? (
                            <span className="inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-medium bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-300">
                              <Bot size={12} /> Auto
                            </span>
                          ) : (
                            <span className="inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-medium bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300">
                              <User size={12} /> Manual
                            </span>
                          )}
                        </td>
                        <td className="px-4 py-3 text-slate-500 italic max-w-xs truncate">
                          "{link.context}"
                        </td>
                        <td className="px-4 py-3 text-slate-500 whitespace-nowrap">
                          {new Date(link.createdAt).toLocaleDateString()}
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>

            {/* Pagination */}
            {interlinkingTotalPages > 1 && (
              <div className="p-4 border-t border-slate-100 dark:border-slate-800 flex justify-center gap-2">
                <Button
                  variant="outline"
                  onClick={() => setInterlinkingPage(p => Math.max(1, p - 1))}
                  disabled={interlinkingPage === 1 || loading}
                  className="px-3"
                >
                  <ChevronLeft size={16} /> Previous
                </Button>
                <span className="flex items-center px-4 text-sm font-medium">
                  Page {interlinkingPage} of {interlinkingTotalPages}
                </span>
                <Button
                  variant="outline"
                  onClick={() => setInterlinkingPage(p => Math.min(interlinkingTotalPages, p + 1))}
                  disabled={interlinkingPage === interlinkingTotalPages || loading}
                  className="px-3"
                >
                  Next <ChevronRight size={16} />
                </Button>
              </div>
            )}
          </Card>
          
          {/* Information Card */}
          <Card className="p-6 bg-blue-50 dark:bg-blue-900/10 border border-blue-100 dark:border-blue-900/20">
            <h3 className="font-semibold text-blue-800 dark:text-blue-300 mb-2 flex items-center gap-2">
              <Bot size={18} />
              How Auto-Interlinking Works
            </h3>
            <ul className="list-disc list-inside text-sm text-blue-700 dark:text-blue-400 space-y-1">
              <li>The system analyzes your content daily at 3:00 AM (server time).</li>
              <li>It connects posts that share similar tags and categories.</li>
              <li>Links are created contextually where the related post title appears in the content.</li>
              <li>Existing auto-generated links are refreshed to ensure relevance.</li>
              <li>Manual links are never overwritten or deleted by the AI system.</li>
            </ul>
          </Card>
        </div>
      )}

      {activeTab === 'sitemap' && (
        <div className="space-y-6">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div>
              <h2 className="text-2xl font-semibold text-slate-900 dark:text-white">XML Sitemap Control</h2>
              <p className="text-slate-600 dark:text-slate-400">
                Manage sitemap scope, exclusions, and manual URLs directly from the admin panel.
              </p>
            </div>
            <div className="flex flex-wrap gap-2">
              <Button variant="outline" onClick={loadSitemapConfig} disabled={sitemapLoading}>
                Refresh
              </Button>
              <Button onClick={handleGenerateSitemap} isLoading={sitemapSaving}>
                Generate Sitemap
              </Button>
            </div>
          </div>

          <Card>
            <CardHeader>
              <CardTitle>Current Sitemap Stats</CardTitle>
            </CardHeader>
            <CardContent>
              {sitemapStats ? (
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
                  <div>
                    <div className="text-muted-foreground">Total URLs</div>
                    <div className="text-2xl font-semibold">{sitemapStats.totalUrls}</div>
                  </div>
                  <div>
                    <div className="text-muted-foreground">Blog Posts</div>
                    <div className="text-2xl font-semibold">{sitemapStats.blogPosts ?? 0}</div>
                  </div>
                  <div>
                    <div className="text-muted-foreground">Categories</div>
                    <div className="text-2xl font-semibold">{sitemapStats.categories ?? 0}</div>
                  </div>
                  <div>
                    <div className="text-muted-foreground">Tags</div>
                    <div className="text-2xl font-semibold">{sitemapStats.tags ?? 0}</div>
                  </div>
                  <div>
                    <div className="text-muted-foreground">Pages</div>
                    <div className="text-2xl font-semibold">{sitemapStats.pages ?? 0}</div>
                  </div>
                  <div>
                    <div className="text-muted-foreground">Custom URLs</div>
                    <div className="text-2xl font-semibold">{sitemapStats.customUrls ?? 0}</div>
                  </div>
                  <div className="md:col-span-2">
                    <div className="text-muted-foreground">Base URL</div>
                    <div className="text-sm font-medium break-all">{sitemapStats.baseUrl || 'Not set'}</div>
                  </div>
                </div>
              ) : (
                <div className="text-sm text-muted-foreground">Loading sitemap stats...</div>
              )}
              {sitemapStats?.lastGenerated && (
                <p className="mt-4 text-xs text-muted-foreground">
                  Last generated: {new Date(sitemapStats.lastGenerated).toLocaleString()}
                </p>
              )}
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Configuration</CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="flex items-center gap-3">
                <input
                  type="checkbox"
                  checked={sitemapConfig.enabled}
                  onChange={(e) => setSitemapConfig((prev) => ({ ...prev, enabled: e.target.checked }))}
                />
                <span className="text-sm text-slate-700 dark:text-slate-300">
                  Enable sitemap generation
                </span>
              </div>

              <div className="space-y-2">
                <label className="text-sm font-medium">Base URL override</label>
                <Input
                  placeholder="https://www.example.com"
                  value={sitemapConfig.baseUrl}
                  onChange={(e) => setSitemapConfig((prev) => ({ ...prev, baseUrl: e.target.value }))}
                />
              </div>

              <div className="grid grid-cols-2 md:grid-cols-5 gap-4 text-sm">
                {Object.entries(sitemapConfig.include).map(([key, value]) => {
                  const includeKey = key as keyof SitemapConfigState['include'];
                  return (
                    <label key={key} className="flex items-center gap-2">
                      <input
                        type="checkbox"
                        checked={value}
                        onChange={(e) =>
                          setSitemapConfig((prev) => ({
                            ...prev,
                            include: { ...prev.include, [includeKey]: e.target.checked },
                          }))
                        }
                      />
                      <span className="capitalize">{key.replace(/([A-Z])/g, ' $1')}</span>
                    </label>
                  );
                })}
              </div>

              <div className="grid gap-4 md:grid-cols-2">
                <div className="space-y-2">
                  <label className="text-sm font-medium">Exclude posts (slugs)</label>
                  <Input
                    placeholder="post-slug-one, post-slug-two"
                    value={sitemapConfig.exclude.posts}
                    onChange={(e) => setSitemapConfig((prev) => ({ ...prev, exclude: { ...prev.exclude, posts: e.target.value } }))}
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-medium">Exclude pages (slugs)</label>
                  <Input
                    placeholder="about-us, terms"
                    value={sitemapConfig.exclude.pages}
                    onChange={(e) => setSitemapConfig((prev) => ({ ...prev, exclude: { ...prev.exclude, pages: e.target.value } }))}
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-medium">Exclude categories (slugs)</label>
                  <Input
                    placeholder="interior, exterior"
                    value={sitemapConfig.exclude.categories}
                    onChange={(e) => setSitemapConfig((prev) => ({ ...prev, exclude: { ...prev.exclude, categories: e.target.value } }))}
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-medium">Exclude tags (slugs)</label>
                  <Input
                    placeholder="diy, tips"
                    value={sitemapConfig.exclude.tags}
                    onChange={(e) => setSitemapConfig((prev) => ({ ...prev, exclude: { ...prev.exclude, tags: e.target.value } }))}
                  />
                </div>
              </div>

              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <h4 className="text-sm font-semibold">Custom URLs</h4>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() =>
                      setSitemapConfig((prev) => ({
                        ...prev,
                        customUrls: [...prev.customUrls, { loc: '', changefreq: 'monthly', priority: '0.5' }],
                      }))
                    }
                  >
                    Add URL
                  </Button>
                </div>
                {sitemapConfig.customUrls.length === 0 ? (
                  <p className="text-xs text-muted-foreground">No custom URLs added yet.</p>
                ) : (
                  <div className="space-y-3">
                    {sitemapConfig.customUrls.map((entry, idx) => (
                      <div key={`${entry.loc}-${idx}`} className="grid grid-cols-1 md:grid-cols-10 gap-3 items-center">
                        <div className="md:col-span-5">
                          <Input
                            placeholder="/custom-path"
                            value={entry.loc}
                            onChange={(e) => {
                              const value = e.target.value;
                              setSitemapConfig((prev) => {
                                const customUrls = [...prev.customUrls];
                                customUrls[idx] = { ...customUrls[idx], loc: value };
                                return { ...prev, customUrls };
                              });
                            }}
                          />
                        </div>
                        <div className="md:col-span-3">
                          <select
                            value={entry.changefreq}
                            onChange={(e) => {
                              const value = e.target.value;
                              setSitemapConfig((prev) => {
                                const customUrls = [...prev.customUrls];
                                customUrls[idx] = { ...customUrls[idx], changefreq: value };
                                return { ...prev, customUrls };
                              });
                            }}
                            className="w-full px-3 py-2 border border-border rounded-lg bg-background text-sm"
                          >
                            {CHANGEFREQ_OPTIONS.map((option) => (
                              <option key={option} value={option}>
                                {option}
                              </option>
                            ))}
                          </select>
                        </div>
                        <div className="md:col-span-1">
                          <Input
                            type="number"
                            min="0"
                            max="1"
                            step="0.1"
                            value={entry.priority}
                            onChange={(e) => {
                              const value = e.target.value;
                              setSitemapConfig((prev) => {
                                const customUrls = [...prev.customUrls];
                                customUrls[idx] = { ...customUrls[idx], priority: value };
                                return { ...prev, customUrls };
                              });
                            }}
                          />
                        </div>
                        <div className="md:col-span-1">
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={() =>
                              setSitemapConfig((prev) => ({
                                ...prev,
                                customUrls: prev.customUrls.filter((_, index) => index !== idx),
                              }))
                            }
                          >
                            Remove
                          </Button>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {sitemapMessage && (
                <div className="text-xs text-emerald-600">{sitemapMessage}</div>
              )}

              <div className="flex flex-wrap gap-2">
                <Button onClick={handleSaveSitemapConfig} isLoading={sitemapSaving}>
                  Save Settings
                </Button>
                <Button variant="outline" onClick={() => window.open('/sitemap.xml', '_blank')}>
                  View sitemap.xml
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      )}
    </div>
  );
}


